### ISSUE TITLE
Spec for demonstration interview protocol

### ISSUE THREAD

**Issue by jthrilly** [codaco/NetworkCanvas#131]
We need each step of the interview to be specified, with reference to existing netcanvas-r functionality. For example

Stage 1: Name generator personal
Title: Name Generator Personal
Prompt: Who are the people you have felt close to?
Sub-prompt: This could be a member of your family, a friend, or a neighbor.

If you aren't sure of the required fields for a given interface, just try to guess from what is visible in netcanvas-r.

**Comment by berniehogan** [comment]
## Screen: {static text}

**Introduction**

This demonstration shows some of the features of Network Canvas. The demonstration is based on the 2004 General Social Survey

We have made some slight changes to these questions. If you are interested, contact us to see the differences and a discussion of these. This discussion can be found here: <link to forthcoming github discussion>

Please note: 
Data from this demonstration will be stored locally and will appear next time you open Network Canvas unless you explicitly reset session. Data is never uploaded to a third party. This is done by clicking [GEAR ICON] and selecting [RESET SESSION]. 

To begin click the > on the right hand side. 

## Screen: {roster-based context generator; i.e. RADAR drug select}

We would like to know something about the groups and organizations to which individuals belong. Here is a list of various kinds of organizations. Could you tell me whether or not you are a member of each type?
 

- Fraternal groups
- Service clubs
- Verterans’ groups
- Political clubs 
- Labor unions
- Sports groups 
- Youth groups 
- School service groups
- Hobby or garden clubs
- School fraternities or sororities
- Nationality groups
- Farm organizations. 
- Literary, art, discussion, or study groups 
- Professional or academic societies. 
- Church affiliated groups 
- Any other group. 

## Screen: {name generator} 

From time to time, most people discuss important matters with other people. Looking back over the last six months — who are the people with whom you discussed matters important to you? 

	Alter pop-up dialogue:

	Name: 
	Nickname: <auto-generated from name a la Josh D.PHil>
	Age: <grey text: in years> 
	How long have you known each other: <text field, accepts numbers; grey text: in years]

	[Set Relationship Roles]

		Panel Flip:
		- Spouse
		- Parent 
		- Sibling 
		- Child
		- Other family
		- Co-worker
		- Member of group
		- Neighbor
		- Friend
		- Advisor
		- Other 

	[Context generator-based circles for affiliations]

## Screen: {concentric circles layout}

Please arrange the people on the screen. You can arrange them anywhere, but it is easiest to place people who know each other near each other. Leave lots of room between people. 

## Screen: {static Text}

On the next screen you can draw a line between people by selecting one node and then selecting a second node. 

￼< Screen shot of adding nodes or looping gif of node selecting / edge adding > 

## Screen: {edge generation}

Please draw a line between people who are *especially close* to each other

## Screen: {ordinal bin} 

On average, how often do you usually talk to:
- Almost every day
- At least once a week
- At least once a monnth
- Less than once a month

## Screen: {map: global} 

In which country does the person live? 
Country select as polygon. 

## Screen: {ordinal bin} 

As far as you know, please select highest level of education for each person: 
[NOTE: GSS collapsed due to too many categories]
- Less than high school
- High School graduate
- Some college
- College diploma or Bachelor’s Degree
- Graduate or professional degree

## Screen: {categorical bin}
[NOTE: GSS Vetoed in favor of RADAR due to sensitivity] 

Please specify how these people currently identify their gender
- Female
- Male
- Transgender: Female to male
- Transgender: Male to female
- Don't know
- Not listed
